Repository nimblehq/liveman-demo-api, pull requests merged in 2021-07, with the labels that each got.

#9 [2] Setup docker for development
  .sobelow-conf
  coveralls.json
  docker-compose.dev.yml
  liveman_api/.formatter.exs
  liveman_api/.gitignore
  liveman_api/README.md
  liveman_api/lib/liveman_api.ex
  liveman_api/mix.exs
  liveman_api/test/liveman_api_test.exs
  liveman_api/test/test_helper.exs
  mix.exs
  mix.lock
  notebook/API.livemd
Labels: type : feature

#25 [7] Create API endpoint for GET Surveys
  .credo.exs
  lib/liveman/survey/schemas/question.ex
  lib/liveman/survey/schemas/survey.ex
  lib/liveman/survey/surveys.ex
  lib/liveman_web/controllers/v1/survey_controller.ex
  lib/liveman_web/factory.ex
  lib/liveman_web/router.ex
  lib/liveman_web/views/v1/question_view.ex
  lib/liveman_web/views/v1/survey_view.ex
  mix.exs
  mix.lock
  priv/repo/data/surveys.json
  test/liveman/survey/schemas/survey_test.exs
  test/liveman/survey/surveys_test.exs
  test/liveman/user/schemas/question_test.exs
  test/liveman_web/requests/v1/survey_request_test.exs
  test/support/factories/question_factory.ex
  test/support/factories/survey_factory.ex
  test/support/factory.ex
Labels: type : feature

#23 [4] Create Liveman API request client wrapper
  Makefile
  docker-compose.dev.yml
  liveman_api/lib/liveman_api.ex
  liveman_api/mix.exs
  liveman_api/mix.lock
  liveman_api/test/liveman_api_test.exs
  notebook/API.livemd
Labels: type : feature

#13 [8] Create API endpoint for POST Surveys Response
  lib/liveman/survey/surveys.ex
  lib/liveman_web/controllers/v1/answer_controller.ex
  lib/liveman_web/router.ex
  lib/liveman_web/views/v1/error_view.ex
  test/liveman/survey/surveys_test.exs
  test/liveman_web/requests/v1/answer_request_test.exs
Labels: type : feature

#26 [17] As a user, I need to authenticate to make a request
  lib/liveman_web/plugs/auth.ex
  lib/liveman_web/router.ex
  test/liveman_web/plugs/auth_test.exs
  test/liveman_web/requests/v1/answer_request_test.exs
  test/liveman_web/requests/v1/user_request_test.exs
  test/support/api_helper.ex
  test/support/conn_case.ex
Labels: type : feature

#28 Fix file reading
  lib/liveman/survey/surveys.ex
Labels: type : bug

#34 Use runtime code while reading file
  lib/liveman/survey/surveys.ex
Labels: type : bug

#30 [15] Document the API endpoint GET v1/surveys
  notebook/API.livemd
Labels: type : chore

#33 [22] Create a custom Docker image for Livebook
  docker-compose.dev.yml
  liveman_api/Dockerfile
Labels: type : chore

#29 [18] Deploy Liveman Demo API + API documentation
  .dockerignore
  .gitignore
  Dockerfile
  config/prod.exs
  config/runtime.exs
  docker-compose.yml
Labels: type : chore

#31 [5] Create cumbersome API endpoint for Sign Up
  lib/liveman/user/schemas/user_schema.ex
  lib/liveman/user/users.ex
  lib/liveman_web/controllers/v1/user_controller.ex
  lib/liveman_web/helpers/ecto_helpers.ex
  lib/liveman_web/router.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20210729101154_craete_users_table.exs
  test/liveman/user/schemas/user_test.exs
  test/liveman/user/users_test.exs
  test/liveman_web/helpers/ecto_helpers_test.exs
  test/liveman_web/requests/v1/user_request_test.exs
  test/support/factories/user_factory.ex
Labels: type : feature

#32 [16] Document the API endpoint POST v1/surveys
  liveman_api/lib/liveman_api.ex
  notebook/API.livemd
Labels: type : chore

#36 [21] Create/update for the API authentication
  notebook/API.livemd
Labels: type : chore
